version: '3.8'
services:
  app:
    build: .
    container_name: b2b-app
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI= {{ MONGO_URI }}
      - NODE_ENV= {{ NODE_ENV }}
    volumes:
      - ./uploads:/app/uploads