version: '3.8'
services:
  app:
    build: .
    container_name: b2b-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI
      - NODE_ENV
    volumes:
      - mymerch-volume:/app/uploads

volumes:
  mymerch-volume:
    external: true # This tells Docker Compose that 'my-koyeb-volume' is managed externally (by Koyeb)